version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: master
    labels:
      - "test:full"
    open-pull-requests-limit: 5

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: 3006.x
    labels:
      - "test:full"
    open-pull-requests-limit: 5
