# Probot Stale configuration file

# Number of days of inactivity before an issue becomes stale
# 480 is approximately 1 year and 4 months
daysUntilStale: 480

# Number of days of inactivity before a stale issue is closed
daysUntilClose: 7

# Issues with these labels will never be considered stale
#exemptLabels:
#  - pinned
#  - security

# Label to use when marking an issue as stale
staleLabel: stale

# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: |
  This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions.

  If this issue is closed prematurely, please leave a comment and we will gladly reopen the issue.

# Comment to post when removing the stale label. Set to `false` to disable
unmarkComment: |
  Thank you for updating this issue. It is no longer marked as stale.

# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: false

# Limit to only `issues` or `pulls`
only: issues

