version: "2"

exclude_patterns:
  - "*.js"
  - "*.rb"
  - "*.php"

plugins:
  radon:
    enabled: true
    exclude_patterns:
      - "templates/"
    config:
      threshold: "D"

checks:
  argument-count:
    enabled: false
  similar-code:
    config:
      threshold: 40
