codecov:
  ci:
    - drone.saltstack.com
    - jenkinsci.saltstack.com

  branch: develop

  notify:
    require_ci_to_pass: no

ignore:
  - ^*.py$
  - doc/.*
  - tests/.*

coverage:
  round: up
  range: 70..100
  precision: 2

  status:
      project:                   # measuring the overall project coverage
        default:
          enabled: yes           # must be yes|true to enable this status
          if_no_uploads: error   # will post commit status of "error" if no coverage reports we uploaded
                                 # options: success, error, failure
          if_not_found: success  # if parent is not found report status as success, error, or failure
          if_ci_failed: success  # if ci fails report status as success, error, or failure

      patch:                     # pull requests only: this commit status will measure the
                                 # entire pull requests Coverage Diff. Checking if the lines
                                 # adjusted are covered at least X%.
        default:
          enabled: no              # must be yes|true to enable this status
          target: 80%              # specify the target "X%" coverage to hit
          if_no_uploads: error     # will post commit status of "error" if no coverage reports we uploaded
                                   # options: success, error, failure
          if_not_found: success
          if_ci_failed: success

      changes:                   # if there are any unexpected changes in coverage
        default:
          enabled: no            # must be yes|true to enable this status
          if_no_uploads: success
          if_not_found: success
          if_ci_failed: success

# No commends because we're not yet running the full test suite on PRs
comment: off
