---
stages:
  - lint
  - test

include:
  - local: 'cicd/kitchen_template.yml'
  - local: 'cicd/kitchen_testruns.yml'

# pre-commit-run-all:
#   image:
#     name: registry.gitlab.com/saltstack/pop/cicd/containers/ubuntu1804:latest
#     entrypoint: [""]
#   stage: lint
#   variables:
#     PRE_COMMIT_HOME: "${CI_PROJECT_DIR}/pre-commit-cache"
#   only:
#     refs:
#       - merge_requests
#   cache:
#     key: pre-commit-cache
#     paths:
#       - pre-commit-cache/
#   script:
#     - pip3 install pre-commit
#     - pre-commit run -a -v --color always

lint-salt-full:
  image: registry.gitlab.com/saltstack/pop/cicd/containers/ubuntu1804:latest
  stage: lint
  tags:
    - saltstack-internal
  cache:
    key: nox-lint-cache
    paths:
      - .nox
  only:
    refs:
      - schedules
  script:
    - python --version
    - pip3 install -U nox-py2==2019.6.25
    - nox --version
    - nox --install-only -e lint-salt
    - EC=254
    - export PYLINT_REPORT=pylint-report-salt-full.log
    - nox -e lint-salt
    - EC=$?
    - exit $EC

lint-tests-full:
  image: registry.gitlab.com/saltstack/pop/cicd/containers/ubuntu1804:latest
  stage: lint
  tags:
    - saltstack-internal
  cache:
    key: nox-lint-cache
    paths:
      - .nox
  only:
    refs:
      - schedules
  script:
    - python --version
    - pip3 install -U nox-py2==2019.6.25
    - nox --version
    - nox --install-only -e lint-tests
    - EC=254
    - export PYLINT_REPORT=pylint-report-tests-full.log
    - nox -e lint-tests
    - EC=$?
    - exit $EC

docs-build-html:
  image: registry.gitlab.com/saltstack/pop/cicd/containers/ubuntu1804:latest
  stage: test
  tags:
    - saltstack-internal
  cache:
    key: nox-docs-cache
    paths:
      - .nox
  only:
    refs:
      - schedules
  script:
    - python --version
    - pip install -U nox-py2==2019.6.25
    - nox --version
    - nox -e 'docs-html(compress=True)'

docs-build-man-pages:
  image: registry.gitlab.com/saltstack/pop/cicd/containers/ubuntu1804:latest
  stage: test
  tags:
    - saltstack-internal
  cache:
    key: nox-docs-cache
    paths:
      - .nox
  only:
    refs:
      - schedules
  script:
    - python --version
    - pip install -U nox-py2==2019.6.25
    - nox --version
    - nox -e 'docs-man(compress=True, update=False)'
