---
<% vagrant = system('gem list -i kitchen-vagrant 2>/dev/null >/dev/null') %>
<% version = '2018.3.3' %>
<% platformsfile = ENV['SALT_KITCHEN_PLATFORMS'] || '.kitchen/platforms.yml' %>
<% driverfile = ENV['SALT_KITCHEN_DRIVER'] || '.kitchen/driver.yml' %>
<% verifierfile = ENV['SALT_KITCHEN_VERIFIER'] || '.kitchen/verifier.yml' %>

<% if File.exists?(driverfile) %>
<%= ERB.new(File.read(driverfile)).result %>
<% else %>
driver:
  name: docker
  use_sudo: false
  hostname: salt
  privileged: true
  username: kitchen
  volume:
    - /var/run/docker.sock:/docker.sock
  cap_add:
    - sys_admin
  disable_upstart: false
  provision_command:
    - echo 'L /run/docker.sock - - - - /docker.sock' > /etc/tmpfiles.d/docker.conf
transport:
  name: rsync
<% end %>

provisioner:
  name: salt_solo
  salt_version: latest
  salt_install: bootstrap
  run_salt_call: false
  install_after_init_environment: true
  log_level: info
  sudo: true
  require_chef: false
  retry_on_exit_code:
    - 139
  max_retries: 2
  salt_copy_filter:
    - __pycache__
    - '*.pyc'
    - .bundle
    - .tox
    - .nox
    - .kitchen
    - artifacts
    - Gemfile.lock
  # Remote states needs to be defined and under it testingdir or else
  # the local directory isn't copied over to the VM's/Containers that
  # get spun up.
  remote_states:
    testingdir: /testing
  pillars:
    jenkins.sls:
      testing_dir: "{{salt.config.get('root_dir')|replace('\\', '\\\\')}}/testing"
  state_top: {}
<% if File.exists?(platformsfile) %>
<%= ERB.new(File.read(platformsfile)).result %>
<% else %>
platforms:
  - name: fedora
    driver_config:
      image: fedora:latest
      run_command: /usr/lib/systemd/systemd
    provisioner:
      salt_bootstrap_options: -X -p rsync git v<%= version %> >/dev/null
  - name: centos-7
    driver_config:
      run_command: /usr/lib/systemd/systemd
  - name: centos-6
    driver_config:
      run_command: /sbin/init
      provision_command:
        - yum install -y upstart
    provisioner:
      salt_bootstrap_options: -P -p rsync -y -x python2.7 -X git v<%= version %> >/dev/null
  - name: ubuntu-18.04
    driver_config:
      run_command: /lib/systemd/systemd
  - name: ubuntu-16.04
    driver_config:
      run_command: /lib/systemd/systemd
  - name: ubuntu-14.04
    driver_config:
      run_command: /sbin/init
      provision_command:
        - rm -f /sbin/initctl
        - dpkg-divert --local --rename --remove /sbin/initctl
  - name: debian-8
    driver_config:
      run_command: /lib/systemd/systemd
      provision_command:
        - apt-get install -y dbus
        - echo 'L /run/docker.sock - - - - /docker.sock' > /etc/tmpfiles.d/docker.conf
  - name: debian-9
    driver_config:
      run_command: /lib/systemd/systemd
  - name: arch
    driver_config:
      image: saltstack/ci-arch:2019.2
      provision_command:
        - systemctl enable sshd
        - echo 'L /run/docker.sock - - - - /docker.sock' > /etc/tmpfiles.d/docker.conf
    provisioner:
      salt_bootstrap_options: -X -p rsync git v<%= version %> >/dev/null
  - name: opensuse-15
    driver_config:
      image: opensuse/leap:15.0
      run_command: /usr/lib/systemd/systemd
      provision_command:
        - zypper --non-interactive install --auto-agree-with-licenses dbus-1
        - systemctl enable sshd.service
        - echo 'L /run/docker.sock - - - - /docker.sock' > /etc/tmpfiles.d/docker.conf
    provisioner:
      salt_bootstrap_options: -qXU -x python2 git v<%= @version %>
  - name: opensuse-42.3
    driver_config:
      image: opensuse/leap:42.3
      run_command: /usr/lib/systemd/systemd
      provision_command:
        - zypper --non-interactive install --auto-agree-with-licenses dbus-1
        - systemctl enable sshd.service
        - echo 'L /run/docker.sock - - - - /docker.sock' > /etc/tmpfiles.d/docker.conf
<% if vagrant != false %>
  - name: windows-2012r2
    driver:
      box: mwrock/Windows2012R2
      name: vagrant
      gui: true
    transport:
      name: winrm
      username: Administrator
      password: Pass@word1
    provisioner:
      init_environment: |
        Clear-Host
        $AddedLocation ="c:\salt;c:\salt\bin\Scripts"
        $Reg = "Registry::HKLM\System\CurrentControlSet\Control\Session Manager\Environment"
        $OldPath = (Get-ItemProperty -Path $Reg -Name PATH).Path
        $NewPath= $OldPath + ";" + $AddedLocation
        Set-ItemProperty -Path $Reg -Value $NewPath -Name PATH
        reg add "hklm\system\currentcontrolset\control\session manager\memory management" /v pagingfiles /t reg_multi_sz /d "d:\pagefile.sys 4096 8192" /f
        winrm set winrm/config/winrs '@{MaxMemoryPerShellMB="5000"}'
      salt_bootstrap_url: https://raw.githubusercontent.com/saltstack/salt-bootstrap/develop/bootstrap-salt.ps1
      salt_bootstrap_options: ''
  - name: windows-2016
    driver:
      box: mwrock/Windows2016
      name: vagrant
      gui: true
      customize:
        cpus: 4
        memory: 8192
    transport:
      name: winrm
      username: Vagrant
      password: vagrant
    provisioner:
      salt_bootstrap_url: https://raw.githubusercontent.com/saltstack/salt-bootstrap/develop/bootstrap-salt.ps1
      salt_bootstrap_options: -version <%= version %>
      init_environment: |
        Clear-Host
        $AddedLocation ="c:\salt;c:\salt\bin\Scripts"
        $Reg = "Registry::HKLM\System\CurrentControlSet\Control\Session Manager\Environment"
        $OldPath = (Get-ItemProperty -Path $Reg -Name PATH).Path
        $NewPath= $OldPath + ";" + $AddedLocation
        Set-ItemProperty -Path $Reg -Value $NewPath -Name PATH
        reg add "hklm\system\currentcontrolset\control\session manager\memory management" /v pagingfiles /t reg_multi_sz /d "d:\pagefile.sys 4096 8192" /f
        winrm set winrm/config/winrs '@{MaxMemoryPerShellMB="5000"}'
      salt_bootstrap_url: https://raw.githubusercontent.com/saltstack/salt-bootstrap/develop/bootstrap-salt.ps1
      salt_bootstrap_options: ''
<% end %>
<% end %>
suites:
  - name: py2
  - name: py3
    excludes:
      - centos-6
      - ubuntu-14.04
<% if File.exists?(verifierfile) %>
<%= ERB.new(File.read(verifierfile)).result %>
<% else %>
verifier:
  name: nox
  run_destructive: true
  coverage: true
  junitxml: true
  sudo: true
  transport: zeromq
  sysinfo: true
  sys_stats: true
<% end %>
