---
name: release-changes
description: Create release changes diff
inputs:
  salt-version:
    type: string
    required: true
    description: The Salt version to set prior to creating the release changes

runs:
  using: composite

  steps:

    - name: Pip Install Tools Requirements
      shell: bash
      run: |
        pip3 install -r $(pwd)/requirements/static/ci/py3.10/tools.txt
        pip3 install -r $(pwd)/requirements/static/ci/py3.10/changelog.txt
        pip3 install -r $(pwd)/requirements/static/ci/py3.10/docs.txt

    - name: Set salt version
      shell: bash
      run: |
          echo '${{ inputs.salt-version }}' > salt/_version.txt

    - name: Update Debian changelog
      shell: bash
      run: |
        tools changelog update-deb --draft
        tools changelog update-deb

    - name: Update RPM changelog
      shell: bash
      run: |
        tools changelog update-rpm --draft
        tools changelog update-rpm

    - name: Update Release Notes
      shell: bash
      run: |
        tools changelog update-release-notes --draft
        tools changelog update-release-notes

    - name: Update CHANGELOG.md
      shell: bash
      run: |
        tools changelog update-release-notes --draft
        tools changelog update-release-notes

    - name: Update CHANGELOG.md
      shell: bash
      run: |
        tools docs man

    - name: Create release changes diff
      shell: bash
      run: |
        git diff --no-color > salt-${{ inputs.salt-version }}.diff

    - name: Upload Source Tarball as an Artifact
      uses: actions/upload-artifact@v3
      with:
        name: salt-${{ inputs.salt-version }}.diff
        path: salt-${{ inputs.salt-version }}.diff
        retention-days: 7
        if-no-files-found: error
