#! /usr/bin/dh-exec

pkg/common/logrotate/salt-common /etc/logrotate.d
pkg/common/fish-completions/salt-cp.fish /usr/share/fish/vendor_completions.d
pkg/common/fish-completions/salt-call.fish /usr/share/fish/vendor_completions.d
pkg/common/fish-completions/salt-syndic.fish /usr/share/fish/vendor_completions.d
pkg/common/fish-completions/salt_common.fish /usr/share/fish/vendor_completions.d
pkg/common/fish-completions/salt-minion.fish /usr/share/fish/vendor_completions.d
pkg/common/fish-completions/salt-key.fish /usr/share/fish/vendor_completions.d
pkg/common/fish-completions/salt-master.fish /usr/share/fish/vendor_completions.d
pkg/common/fish-completions/salt-run.fish /usr/share/fish/vendor_completions.d
pkg/common/fish-completions/salt.fish /usr/share/fish/vendor_completions.d
