title: "[Bug]"
labels: [Bug]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        A clear and concise description of what the bug is.
  - type: textarea
    id: setup
    attributes:
      label: Setup
      description: |
        Relevant configs and/or SLS files (be sure to remove sensitive info.
        There is no general set-up of Salt. Please be as specific as possible
        and give set-up details.
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: |
         Steps to reproduce the behaviour. Include debug logs if possible and relevant
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
  - type: textarea
    id: versions
    attributes:
      label: Versions Report(s)
      description: Versions reports for any affected components (master, minsions, ect).
      value: |
        `salt --versions-report`
        ```yaml
        PASTE HERE
        ```
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      placeholder: If applicable, add screenshots to help explain your problem.
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
