---
name: build-source-tarball
description: Build Source Tarball
inputs:
  salt-version:
    type: string
    required: true
    description: The Salt version to set prior to building the tarball.
  nox-version:
    required: false
    type: string
    description: The version of Nox to install
    default: "2022.8.7"


env:
  COLUMNS: 160
  PIP_INDEX_URL: https://pypi-proxy.saltstack.net/root/local/+simple/
  PIP_EXTRA_INDEX_URL: https://pypi.org/simple


runs:
  using: composite

  steps:

    - name: Install Nox
      shell: bash
      run: |
        nox --version || python3 -m pip install nox==${{ inputs.nox-version }}

    - name: Download Release Patch
      uses: actions/download-artifact@v3
      with:
        name: salt-${{ inputs.salt-version }}.patch

    - name: Configure Git
      shell: bash
      run: |
        git config --global user.name "Salt Project Packaging"
        git config --global user.email saltproject-packaging@vmware.com

    - name: Apply Release Patch
      shell: bash
      run: |
        git am --committer-date-is-author-date salt-${{ inputs.salt-version }}.patch
        rm salt-${{ inputs.salt-version }}.patch

    - name: Create Source Tarball
      shell: bash
      run: |
        nox -e build

    - name: Create Hash Files
      shell: bash
      run: |
        tools pkg generate-hashes dist/salt-${{ inputs.salt-version }}.tar.gz

    - name: Upload Source Tarball as an Artifact
      uses: actions/upload-artifact@v3
      with:
        name: salt-${{ inputs.salt-version }}.tar.gz
        path: dist/salt-*.tar.gz*
        retention-days: 7
        if-no-files-found: error
