---
name: get-pull-test-labels
description: Get Pull Test Labels
inputs:
  pull-request:
    type: string

outputs:
    labels:
      value: ${{ steps.get-pull-test-labels.outputs.labels }}

runs:
  using: composite
  steps:
    - name: Get Pull Test Labels
      id: get-pull-test-labels
      shell: bash
      env:
        PULL_REQUEST: ${{ inputs.pull-request }}
      run: |
        labels=$(jq -c '[.labels[].name]' <<< $PULL_REQUEST)
        echo $labels
        echo "labels=$labels" >> "$GITHUB_OUTPUT"
