---
name: setup-relenv
description: Setup Relenv
inputs:
  platform:
    required: true
    type: string
    description: The platform to build
  arch:
    required: true
    type: string
    description: The platform arch to build
  python-version:
    required: true
    type: string
    description: The version of python to build
  cache-seed:
    required: true
    type: string
    description: Seed used to invalidate caches


env:
  PIP_INDEX_URL: https://pypi-proxy.saltstack.net/root/local/+simple/
  PIP_EXTRA_INDEX_URL: https://pypi.org/simple


runs:
  using: composite

  steps:

    - name: Install Relenv
      shell: bash
      run: |
        python3 -m pip install relenv

    - name: Set environment variables
      shell: bash
      run: |
        echo RELENV_VERSION="$(relenv --version)" >> $GITHUB_ENV

    - name: Cache Relenv Data Directory
      uses: actions/cache@v3
      with:
        path: ${{ github.workspace }}/.relenv
        key: ${{ inputs.cache-seed }}|relenv|${{ env.RELENV_VERSION }}|${{ inputs.python-version }}|${{ inputs.platform }}|${{ inputs.arch }}

    - name: Fetch Toolchain
      if: ${{ inputs.platform == 'linux' }}
      shell: bash
      run: |
        python3 -m relenv toolchain fetch --arch=${{ inputs.arch }}

    - name: Fetch Native Python Build
      shell: bash
      run: |
        python3 -m relenv fetch --arch=${{ inputs.arch }} --python=${{ inputs.python-version }}
