.TH salt-master 1 "May 2011" "salt-master 0.8.7" "salt-master Manual"

.SH NAME
salt-master \- The salt master daemon, used to control the salt minions

.SH SYNOPSIS
.B salt-master [ options ]

.SH DESCRIPTION
The master daemon controls the salt minions

.SH OPTIONS
.TP
-h, --help
Print a usage message briefly summarizing these command-line options.

.TP
-d, --daemon
Run the salt master as a daemon

.TP
-c CONFIG, --config=CONFIG
The master configuration file to use, the default is /etc/salt/master


.SH AUTHORS
Thomas S. Hatch <thatch@gmail.com>
