.TH salt-cp 1 "May 2011" "salt 0.8.7" "salt-cp Manual"

.SH NAME
salt-cp \- Copy a file to a set of systems

.SH SYNOPSIS
.B salt-cp '*' [ options ] \fISOURCE DEST\fR

.B salt-cp -E '.*' [ options ] \fISOURCE DEST\fR

.B salt-cp -G 'os:Arch.*' [ options ] \fISOURCE DEST\fR

.SH DESCRIPTION
Salt copy copies a local file out to all of the salt minions matched by the given target.

.SH OPTIONS
.TP
-h, --help
Print a usage message briefly summarizing these command-line options

.TP
-t TIMEOUT, --timeout=TIMEOUT
The timeout in seconds to wait for replies from the salt minions.

.TP
-E, --pcre
The target expresion will be interpereted as a pcre regular expression rather than a shell glob.

.TP
-L, --list
The target expression will be interpereted as a comma delimited list, example: server1.foo.bar,server2.foo.bar,example7.quo.qux

.TP
-G, --grain
The target expression matches values returned by the salt grains system on the minions. The target expresion is in the format of '<grain value>:<pcre regular expresion>'; example: 'os:Arch.*'

.TP
-Q, --query
Execute a salt command query, this can be used to find the results os a previous function call: -Q test.echo')

.TP
-c CONFIG, --config=CONFIG
The location of the salt master configuration file, the salt master settings are required to know where the connections are; default=/etc/salt/master

.SH AUTHORS
Thomas S. Hatch <thatch@gmail.com>
