---
name: get-pull-number
description: Get Pull Number
inputs:
  token:
    type: string
  repo:
    type: string
  owner:
    type: string
  sha:
    type: string
  pull_number:
    default: null

runs:
  using: composite
  steps:
    - name: Get Pull Number
      id: get-pull-number
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
      run: |
        echo ${{ inputs.repo }}
        echo ${{ inputs.owner }}
        echo ${{ inputs.sha }}
        echo ${{ inputs.pull_number }}
        echo NUMBER=$(gh api repos/$repo/$owner/commits/$sha/pulls)
