---
name: get-pull-number
description: Get Pull Number
inputs:
  token:
    type: string
  repo:
    type: string
  owner:
    type: string
  sha:
    type: string
  pull_number:
    default: null

runs:
  using: composite
  steps:
    - name: Get Pull Number
      id: get-pull-number
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
        GITHUB_REPO: ${{ inputs.repo }}
        GITHUB_OWNER: ${{ inputs.owner }}
        GITHUB_SHA: ${{ inputs.sha }}
        GITHUB_PULL_NUMBER: ${{ inputs.pull_number }}
      run: |
        if [ -z "GITHUB_PULL_NUMBER"]
        then
        echo NUMBER=$(gh api repos/$GITHUB_OWNER/$GITHUB_REPO/commits/$GITHUB_SHA/pulls)
        else
        echo NUMBER=$GITHUB_PULL_NUMBER
        fi
