---
name: get-pull-number
description: Get Pull Number
outputs:
  number:
    value: ${{ steps.get-pull-number.outputs.number }}


runs:
  using: composite
  steps:
    - name: Get Pull Number
      id: get-pull-number
      shell: bash
      run:
        echo $GITHUB_PULL_REQUEST_NUMBER
        echo $REPOSITORY_OWNER
        echo $REPOSITORY_NAME
        echo NUMBER=56 >> "$GITHUB_OUTPUT"
