// Generated by CoffeeScript 1.6.3
(function() {
  var mainApp;

  mainApp = angular.module("MainApp");

  mainApp.controller('ProjectCtlr', [
    '$scope', '$location', '$route', 'Configuration', 'SaltApiSrvc', function($scope, $location, $route, Configuration, SaltApiSrvc) {
      $scope.errorMsg = "";
      return true;
    }
  ]);

}).call(this);
