'''
The standard outputter used for keys
'''

# Import salt libs
import salt.utils


def output(data):
    '''
    Read in the dict structure generated by the salt key api methods and
    print the structure.
    '''
    color = salt.utils.get_colors(
                not bool(__opts__.get('no_color', False)))

    cmap = {'minions_pre': color['RED'],
            'minions': color['GREEN'],
            'minions_rejected': color['BLUE']}    

    trans = {'minions_pre': '{0}Unaccepted Keys:{1}'.format(color['LIGHT_RED'], color['ENDC']),
             'minions': '{0}Accepted Keys:{1}'.format(color['LIGHT_GREEN'], color['ENDC']),
             'minions_rejected': '{0}Rejected Keys:{1}'.format(color['LIGHT_BLUE'], color['ENDC'])}

    for status in sorted(data):
        print(trans[status])
        for key in data[status]:
            print('{0}{1}{2}'.format(cmap[status], key, color['ENDC']))
