#!/bin/bash

get_pid() {
	ps aux | grep -v grep | grep '/usr/bin/python2 /usr/bin/salt-master -d' | awk '{print $2}'
}

PID=$(get_pid)
if [ "$PID" ]; then
  kill $PID
  sleep 5
  /usr/bin/salt-master -d
else
  /usr/bin/salt-master -d
fi

