#!/usr/bin/env python2
'''
Manage the authentication keys with salt-key
'''

import salt.cli


def main():
    '''
    The main function
    '''
    saltkey = salt.cli.SaltKey()
    saltkey.run()

if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        raise SystemExit('\nExiting gracefully on Ctrl-c')
