#!/usr/bin/env python2
'''
Execute a salt convenience routine
'''

import salt.cli


def main():
    '''
    The main function
    '''
    client = salt.cli.SaltRun()
    client.run()

if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        raise SystemExit('\nExiting gracefully on Ctrl-c')
