#!/usr/bin/env python
'''
Directly call a salt command in the modules, does not require a running salt
minion to run.
'''
import logging
def myerror(x) :
    raise x
logging.error
logging.error=myerror
print logging.error
#logging.exception

import sys
old_sys_exit = sys.exit
def new_sys_exit (value) : 
    print "in sys exit %s" % value
    #old_sys_exit(value)
    raise Exception("exit!")
sys.exit = new_sys_exit

from salt.scripts import salt_call


if __name__ == '__main__':
    salt_call()
