#!/usr/bin/python2
'''
This script is used to kick off a salt minion daemon
'''
import salt
import os

def main():
    '''
    The main function
    '''
    pid = os.getpid()
    try:
        minion = salt.Minion()
        minion.start()
    except KeyboardInterrupt:
        os.kill(pid, 15)

if __name__ == '__main__':
    main()
