#!/usr/bin/env python

import salt.cloud.cli

def main():
    '''
    The main function for salt-cloud
    '''
    cloud = salt.cloud.cli.SaltCloud()
    cloud.run()

if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        raise SystemExit('\nExiting gracefully on Ctrl-c')
