#!/usr/bin/env python2
'''
Start the salt-master
'''

import salt


def main():
    '''
    The main function
    '''
    master = salt.Master()
    master.start()

if __name__ == '__main__':
    main()
