#!/usr/bin/python
'''
This script is used to kick off a salt syndic daemon
'''

import os
import salt


def main():
    '''
    The main function
    '''
    pid = os.getpid()
    try:
        syndic = salt.Syndic()
        syndic.start()
    except KeyboardInterrupt:
        os.kill(pid, 15)

if __name__ == '__main__':
    main()
