#!/usr/bin/python
'''
Directly call a salt command in the modules, does not require a running salt
minion to run.
'''

import salt.cli
import salt.log
salt.log.setup_console_logger()


def main():
    '''
    The main function
    '''
    client = salt.cli.SaltCall()
    client.run()

if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        raise SystemExit('\nExiting gracefully on Ctrl-c')
