#!/usr/bin/env python
'''
This script is used to kick off a salt syndic daemon
'''


if __name__ == '__main__':
    print("WARNING!\n"
          "Salt Syndic functionality was moved to Salt Master. Salt-syndic script is not needed\n"
          "anymore. To start syndic just start master with syndic_master option set in the master\n"
          "config.")
    exit(1)

