#!/usr/bin/env python2
'''
Directly call a salt command in the modules, does not require a running salt
minion to run.
'''

import salt.cli

def main():
    '''
    The main function
    '''
    client = salt.cli.SaltCall()
    client.run()

if __name__ == '__main__':
    main()
