#!/usr/bin/python
'''
Publish commands to the salt system from the command line on the master.
'''

import salt.cli


def main():
    '''
    The main function
    '''
    client = salt.cli.SaltCMD()
    client.run()

if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        raise SystemExit('\nExiting gracefully on Ctrl-c')
