#!/usr/bin/env python
'''
Publish commands to the salt system from the command line on the master.

.. versionadded:: 2015.8.0
'''

from salt.scripts import salt_spm


if __name__ == '__main__':
    salt_spm()
