#! /bin/env python

import sys
import os
import tarfile
from os.path import dirname, join, abspath
from shutil import copy
from subprocess import check_call

src = abspath(join(dirname(__file__), '../..'))

sys.path.append(src)
import salt.version

salt_version = '.'.join(map(str, salt.version.__version_info__[0:3]))
buildid = 6

rpmbuild = join(os.environ['HOME'], 'rpmbuild')
copy(join(src, 'pkg/rpm/salt.spec'), join(rpmbuild, 'SPECS'))
for f in os.listdir(join(src, 'pkg/rpm')):
    if f in ['salt.spec', 'build']:
        continue
    copy(join(src, 'pkg/rpm', f), join(rpmbuild, 'SOURCES'))

def srcfilter(ti):
    if ti.name.startswith('.git'):
        return None
    return ti

with tarfile.open(join(rpmbuild, 'SOURCES/salt-%s.tar.gz' % salt_version), 'w|gz') as tf:
    tf.add(src, arcname = 'salt-%s' % salt_version,
           filter = srcfilter)

cmd = ['rpmbuild', '-bb',
       '--define=salt_version %s' % salt_version,
       '--define=buildid %s' % buildid,
       'salt.spec']
print "Executing: %s" % " ".join('"%s"' % c for c in cmd)
check_call(cmd, cwd = join(rpmbuild, 'SPECS'))
