---
name: setup-salt-version
description: Setup Salt Version
inputs:
  cwd:
    type: string
    default: ""
  salt-version:
    type: string
    default: ""
    description: >
      The Salt version to set prior to running tests or building packages.
      If not set, it is discover at run time, like, for example, capturing
      the output of running `python3 salt/version.py`
outputs:
  salt-version:
    value: ${{ steps.setup-salt-version.outputs.salt-version }}
    description: The Salt version written to `salt/_version.txt`

runs:
  using: composite

  steps:

    - name: Setup Salt Version
      id: setup-salt-version
      shell: bash
      run: |
        if [ "${{ inputs.cwd }}" != "" ]; then
          cd "${{ inputs.cwd }}"
        fi
        tools pkg set-salt-version ${{ inputs.salt-version }}
