name: Build Salt Packages

on:
  - workflow_call

jobs:
  rpm:
    name: Build RPM
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
          - x86_64

    container:
      image: centos:7

    steps:
      - uses: actions/checkout@v3

      - name: Download System Dependencies
        run: |
          yum -y update
          yum -y install python3 python3-pip openssl git rpmdevtools rpmlint systemd-units

      - name: Build RPM
        env:
          USE_STATIC_REQUIREMENTS: "1"
        run: |
          rpmbuild -bb --define="_salt_src $(pwd)" $(pwd)/pkg/rpm/salt.spec

      - name: Upload RPMs
        uses: actions/upload-artifact@v3
        with:
          name: salt-${{ matrix.arch }}-rpms
          path: ~/rpmbuild/RPMS/${{ matrix.arch }}/*.rpm
          retention-days: 7

      - name: Set Exit Status
        if: always()
        run: |
          python3 -c "import os; os.makedirs('exitstatus', exist_ok=True)"
          echo "${{ job.status }}" > exitstatus/${{ github.job }}-linux-${{ matrix.arch }}

      - name: Upload Exit Status
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: exitstatus
          path: exitstatus
          if-no-files-found: error
