name: PR Checks

on:
  pull_request_target:
    types: [opened, synchronize]

jobs:

  Check-Changed-Files-Docstrings:
    name: Check Docstrings For Changed Files On PR
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Dependencies
        env:
          PIP_EXTRA_INDEX_URL: https://pypi-proxy.saltstack.net/root/local/+simple/
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit pygithub

      - id: changed-files
        name: Get Changed Files
        uses: dorny/paths-filter@v2
        with:
          token: ${{ github.token }}
          list-files: json
          filters: |
            salt:
              - added|modified:
                - 'salt/**'

      - name: Check Docstrings For Changed Files On PR
        id: check-known-missing-docstrings
        if: github.event_name == 'pull_request_target' && steps.changed-files.outputs.salt == 'true'
        continue-on-error: true
        run: |
          pre-commit run -v --hook-stage manual check-known-missing-docstrings --show-diff-on-failure --color=never --files ${{ join(fromJSON(steps.changed-files.outputs.salt_files), ' ') }} | tee output.txt

      - name: Comment on PR
        if: hashFiles('output.txt') != ''
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python .github/workflows/scripts/pr-docstring-comments.py \
            --org ${{ github.repository_owner }} \
            --repo ${{ github.event.repository.name }} \
            --issue ${{ github.event.number }} output.txt
