---
name: Publish Repositories

on:
  workflow_call:
    inputs:
      environment:
        type: string
        description: On which GitHub Environment Context To Run
      salt-version:
        type: string
        required: true
        description: The Salt version

env:
  COLUMNS: 190

jobs:

  publish-repositories:
    name: Publish Repositories
    runs-on:
      - self-hosted
      - linux
      - repo-${{ inputs.environment }}
    environment: ${{ inputs.environment }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Setup Python Tools Scripts
        uses: ./.github/actions/setup-python-tools-scripts

      - name: Download Repository Artifact
        uses: actions/download-artifact@v3
        with:
          name: salt-${{ inputs.salt-version }}-${{ inputs.environment }}-repo
          path: repo/

      - name: Decompress Repository Artifacts
        run: |
          find repo/ -type f -name '*.tar.gz' -print -exec tar xvf {} \;
          find repo/ -type f -name '*.tar.gz' -print -exec rm -f {} \;

      - name: Show Repository
        run: |
          tree -a artifacts/pkgs/repo/

      - name: Upload Repository Contents(${{ inputs.environment }})
        run: |
          tools pkg repo publish ${{ inputs.environment }} \
            ${{ contains(inputs.salt-version, 'rc') && '--rc-build' || '' }} artifacts/pkgs/repo/
