---
name: Publish Repositories

on:
  workflow_call:
    inputs:
      environment:
        type: string
        description: On which GitHub Environment Context To Run
      salt-version:
        type: string
        required: true
        description: The Salt version

env:
  COLUMNS: 160

jobs:

  publish-repositories:
    name: Publish Repositories
    runs-on:
      - self-hosted
      - linux
      - repo-${{ inputs.environment }}
    environment: ${{ inputs.environment }}

    steps:

      - name: Download Repository Artifact
        uses: actions/download-artifact@v3
        with:
          name: salt-${{ inputs.salt-version }}-${{ inputs.environment }}-repo
          path: repo/

      - name: Decompress Repository Artifacts
        run: |
          find repo/ -type f -name '*.tar.gz' -print -exec tar xvf {} \;
          find repo/ -type f -name '*.tar.gz' -print -exec rm -f {} \;

      - name: Show Repository
        run: |
          tree -a artifacts/pkgs/repo/

      - name: Upload Repository Contents(${{ inputs.environment }})
        run: |
          aws s3 cp --color on --acl bucket-owner-full-control --recursive artifacts/pkgs/repo/ s3://salt-project-prod-salt-artifacts-${{ inputs.environment }}
