name: Set Workflow Conclusion

on:
  workflow_call: {}

jobs:
  set-workflow-conclusion:
    name: Set the Pipeline Exit Status
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Get workflow information
        id: get-workflow-info
        uses: technote-space/workflow-conclusion-action@v3

      - name: Set Pipeline Exit Status
        shell: bash
        run: |
          if [ "${{ steps.get-workflow-info.outputs.conclusion }}" != "success" ]; then
            exit 1
          else
            exit 0
          fi

      - name: Done
        if: always()
        run:
          echo "All worflows finished"
