name: SSH Debug
run-name: "SSH Debug ${{ inputs.runner }}"
on:
  workflow_dispatch:
    inputs:
      runner:
        type: string
        required: True
        description: The runner to start a tunnel on.
      offer:
        type: string
        required: True
        description: SDP Offer
      public_key:
        type: string
        required: True
        description: Your public key for ssh access.
      debug:
        required: false
        type: boolean
        default: false
        description: Run sshd with debug enabled.



jobs:
  debug:
    runs-on: ${{ inputs.runner }}
    if: ${{ inputs.runner }}
    environment: ci
    steps:

      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Setup Python Tools Scripts
        uses: ./.github/actions/setup-python-tools-scripts
        with:
          cache-prefix: ssh-debug

      - name: Install Nox
        run: |
          python3 -m pip install 'nox==2022.8.7'
        env:
          PIP_INDEX_URL: https://pypi.org/simple

      - uses: ./.github/actions/ssh-tunnel
        with:
          public_key: ${{ inputs.public_key }}
          offer: ${{ inputs.offer }}
          debug: ${{ inputs.debug }}
