name: Twine Check

on:
  workflow_call:
    inputs:
      changed-files:
        required: true
        type: string
        description: JSON string containing information about changed files

jobs:
  Twine-Check:
    name: Run 'twine check' Against Salt

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      env:
        PIP_EXTRA_INDEX_URL: https://pypi-proxy.saltstack.net/root/local/+simple/
      run: |
        pip install --upgrade pip setuptools wheel
        pip install twine>=3.4.1
        # pip install build     # add build when implement pyproject.toml

    - name: Create Source Tarball
      run: |
        python3 setup.py sdist
        # TBD python3 -m build --sdist  # replace with build when implement pyproject.toml

    - name: Twine check
      run: |
        python3 -m twine check dist/*
